### ISSUE TITLE
DiscordAPIError: Target user is not connected to voice.

### ISSUE THREAD

**Issue by pedrofracassi** [pedrofracassi/amongcord#3]
```
node:20993) UnhandledPromiseRejectionWarning: DiscordAPIError: Target user is not connected to voice.
    at RequestHandler.execute (/home/pedro/amongcord/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

**Comment by ValentinKhmer** [comment]
I think it's normal (this bug don't have a big impact on the bot).
I develop me too a AmongUs Bot and i have a same problem ^^
